name: tilbil
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_launcher_icons: ^0.11.0
  
  #flutter_localizations:
  #  sdk: flutter
  #intl: ^0.17.0
  # svg
  flutter_svg: ^1.1.6
  share_plus: ^6.3.0
  #build_runner:
  #flutter_gen_runner: ^5.1.0+1
  #flutter_gen: ^5.1.0+1
  carousel_slider: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

 
  # example:
  fonts:
    - family: CormorantInfant
      fonts:
        - asset: assets/fonts/CormorantInfant-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
          weight: 700
    - family: Gabriela
      fonts:
        - asset: assets/fonts/Gabriela-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
          weight: 400
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  # flutter pub run flutter_launcher_icons


flutter_gen:
  output: lib/constants/assets/  # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true 