// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ1lBtI21fYHaoqkHv-DnVS3Tw4Oy5c0c',
    appId: '1:698335664514:web:29549333c5bf0c3fd3579b',
    messagingSenderId: '698335664514',
    projectId: 'tilbil-eff89',
    authDomain: 'tilbil-eff89.firebaseapp.com',
    storageBucket: 'tilbil-eff89.appspot.com',
    measurementId: 'G-B08KE6R204',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyR2YoelPRWuGrri9UPJ_anuu6fvLGBho',
    appId: '1:698335664514:android:77f589c6e10f5cdbd3579b',
    messagingSenderId: '698335664514',
    projectId: 'tilbil-eff89',
    storageBucket: 'tilbil-eff89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDovpFwvOYyGDqBh8gGLiUMENsT8ojwJZs',
    appId: '1:698335664514:ios:94a04660e2ff557fd3579b',
    messagingSenderId: '698335664514',
    projectId: 'tilbil-eff89',
    storageBucket: 'tilbil-eff89.appspot.com',
    iosClientId: '698335664514-e372skej5b87cbcu78ekdvu1fvq8n0qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tilbil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDovpFwvOYyGDqBh8gGLiUMENsT8ojwJZs',
    appId: '1:698335664514:ios:94a04660e2ff557fd3579b',
    messagingSenderId: '698335664514',
    projectId: 'tilbil-eff89',
    storageBucket: 'tilbil-eff89.appspot.com',
    iosClientId: '698335664514-e372skej5b87cbcu78ekdvu1fvq8n0qg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tilbil',
  );
}
